import type {
  PerformanceTraceFrameStats,
  PerformanceTracePreset,
  PerformanceTraceSummary,
} from "mcp-devices/adapters/platform-adapter";

const TRACE_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TRACE_ROOT = "/data/misc/perfetto-traces";

const UI_JANK_CATEGORIES = [
  "sched",
  "freq",
  "idle",
  "am",
  "wm",
  "gfx",
  "view",
  "binder_driver",
];

const STARTUP_CATEGORIES = [
  ...UI_JANK_CATEGORIES,
  "dalvik",
  "input",
  "res",
];

export function perfettoRemotePath(traceId: string): string {
  validateTraceId(traceId);
  return `${TRACE_ROOT}/mcp-devices-${traceId}.perfetto-trace`;
}

export function buildPerfettoStartArgs(
  traceId: string,
  preset: PerformanceTracePreset,
  durationMs: number,
  packageName?: string,
): string[] {
  const durationSeconds = Math.ceil(durationMs / 1000);
  const args = [
    "shell",
    "perfetto",
    "--background-wait",
    "--out",
    perfettoRemotePath(traceId),
    "--time",
    `${durationSeconds}s`,
    "--buffer",
    "8mb",
    "--size",
    "24mb",
  ];
  if (packageName) args.push("--app", packageName);
  args.push(...(preset === "startup" ? STARTUP_CATEGORIES : UI_JANK_CATEGORIES));
  return args;
}

export function summarizeAndroidTrace(gfxOutput?: string): PerformanceTraceSummary {
  const frameStats = gfxOutput ? parsePerfettoFrameStats(gfxOutput) : undefined;
  return {
    frameStats,
    warnings: frameStats
      ? []
      : ["Frame statistics were unavailable; inspect the Perfetto artifact for native trace data."],
  };
}

export function parsePerfettoFrameStats(output: string): PerformanceTraceFrameStats | undefined {
  const totalFrames = integerMatch(output, /Total frames rendered:\s*(\d+)/i);
  const jankyFrames = integerMatch(output, /Janky frames:\s*(\d+)/i);
  if (totalFrames === undefined || jankyFrames === undefined) return undefined;

  const reportedPercent = numberMatch(output, /Janky frames:\s*\d+\s*\(([\d.]+)%\)/i);
  const jankyPercent = reportedPercent ?? (totalFrames === 0 ? 0 : (jankyFrames / totalFrames) * 100);
  return {
    totalFrames,
    jankyFrames,
    jankyPercent: round(jankyPercent),
    p50Ms: integerMatch(output, /50th percentile:\s*(\d+)ms/i),
    p90Ms: integerMatch(output, /90th percentile:\s*(\d+)ms/i),
    p95Ms: integerMatch(output, /95th percentile:\s*(\d+)ms/i),
    p99Ms: integerMatch(output, /99th percentile:\s*(\d+)ms/i),
  };
}

function validateTraceId(traceId: string): void {
  if (!TRACE_ID.test(traceId)) {
    throw new Error("Perfetto trace id must be a UUID generated by mcp-devices.");
  }
}

function integerMatch(output: string, pattern: RegExp): number | undefined {
  const value = pattern.exec(output)?.[1];
  if (value === undefined) return undefined;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function numberMatch(output: string, pattern: RegExp): number | undefined {
  const value = pattern.exec(output)?.[1];
  if (value === undefined) return undefined;
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function round(value: number): number {
  return Math.round(value * 10) / 10;
}
